### ISSUE TITLE
mesa.visualization.chartmodule doesn't work

### ISSUE THREAD

**Issue by mikevlan** [projectmesa/mesa#1859]
As shown in the picture, I run the boltzmann_wealth_model in the mesa example, but the line chart is not displayed normally. Can anyone help me?
<img width="788" alt="屏幕截图 2023-11-04 183542" src="https://github.com/projectmesa/mesa/assets/75169342/89ba1b20-4011-471b-909e-5fea97da6b73">

**Comment by mikevlan** [comment]
I have tried it many times, ,all other charts can be displayed normally，except for chartmodule

**Comment by rht** [comment]
That's https://github.com/projectmesa/mesa-viz-tornado/issues/26. A fix has been pushed to https://github.com/projectmesa/mesa-viz-tornado (this is one of Mesa's dependencies). It just hasn't been released on PyPI yet. If you install from the Git repo, it should solve your problem. cc: @tpike3

**Comment by mikevlan** [comment]
> 那是[projectmesa/mesa-viz-tornado#26](https://github.com/projectmesa/mesa-viz-tornado/issues/26)。修复程序已至https://github.com/projectmesa/mesa-viz-tornado（Mesa 的依赖项之一）。只是还没有在 PyPI 上发布。如果您从 Git 存储库安装，它应该可以解决您的问题。抄送：@tpike3

Thank you for your reply. I downloaded the mesa-viz-tornado you mentioned. This solved the label problem, but the line color still cannot be displayed normally.

**Comment by rht** [comment]
Have you made sure to specify as `Color` instead of `color`?

**Comment by mikevlan** [comment]
> Have you made sure to specify as `Color` instead of `color`?

I was so shocked. Today I reopened pycharm and everything showed normal. Anyway, thank you for your reply.

**Comment by mikevlan** [comment]
Now I can run any function of mesa normally, but my mesa shows "cannot find declaration to go to". I don't know if this is a bug or my mistake. Fortunately, the problem is solved.
