### ISSUE TITLE
Slider Bar Visualization is not working

### ISSUE THREAD

**Issue by claywrc** [projectmesa/mesa#419]
Hello - I've copied the code from the advanced tutorial associated with adding an interactive parameter, but when I run the visualization, the "Number of Agents" slider does not appear.  The tutorial does not explicitly say where the UserSettableParameter() should be defined, but I'm assuming it is defined in the server.py file so that it can be passed as a model parameter.  Is there anything else that I might be missing, or anything that might prevent the slider from showing up?  

If it helps, I also tried adjusting the starting value of the slider, and even though I can't see it in the visualization, it seems to have the expected effect on the simulation run.

**Comment by narc98** [comment]
What browser are you using?  I have found that the slider bars do not appear in Edge/Internet Explorer.  I have had no issues with them appearing in Chrome, Firefox, or Opera.

**Comment by claywrc** [comment]
Yep - I'm having the issue with Explorer.  Not necessarily by choice - that's just what my default browser happens to be so that's what the local server launches.  That's easy enough to change on my local machine, but if I wanted to deploy this, would there be a way to detect the default browser and throw an alert, or allow the user to choose another browser?

**Comment by clmerlos** [comment]
You can change `webbrowser.open(url)` from ModularVisualization line 334 to `webbrowser.get('safari').open(url)` or some other browser such as 'chrome' or 'firefox'

**Comment by clmerlos** [comment]
You can change `webbrowser.open(url)` from ModularVisualization line 334 to `webbrowser.get('safari').open(url)` or some other browser such as 'chrome' or 'firefox'

**Comment by clmerlos** [comment]
You can change `webbrowser.open(url)` from ModularVisualization line 334 to `webbrowser.get('safari').open(url)` or some other browser such as 'chrome' or 'firefox'

**Comment by clmerlos** [comment]
You can change `webbrowser.open(url)` from ModularVisualization line 334 to `webbrowser.get('safari').open(url)` or some other browser such as 'chrome' or 'firefox'

**Comment by clmerlos** [comment]
You can change `webbrowser.open(url)` from ModularVisualization line 334 to `webbrowser.get('safari').open(url)` or some other browser such as 'chrome' or 'firefox'

**Comment by clmerlos** [comment]
You can change `webbrowser.open(url)` from ModularVisualization line 334 to `webbrowser.get('safari').open(url)` or some other browser such as 'chrome' or 'firefox'

**Comment by claywrc** [comment]
Thanks for the suggestions - that helps me keep rolling.  Is it strange that the default 'Frames per Second' slider shows up fine in IE, but not any added sliders?  I'm assuming there is a way to get the user-defined sliders to show up.  I'll work on it and post an update if I figure it out.

**Comment by claywrc** [comment]
Does anybody know how to control the layout of several charts on the page instead of having everything run down the center?

**Comment by zyzek** [comment]
You'll need to modify the template in `mesa/visualization/templates/` directly to change the page style.

**Comment by claywrc** [comment]
Thanks for the recommendation - Not sure who to make aware of it, but the github page for that documentation seems to be broken (I'm trying to follow from the link in the tutorial).

**Comment by TaylorMutch** [comment]
@claywrc Thank you for bringing up this issue.

I'm seeing a couple issues lining up with the newer visualization code. One of which is compatibility with Edge. There is a documented [issue with jQuery and Edge ](https://github.com/jquery/jquery/issues/3251), which I am working on, and is related to #415.

In terms of where the `UserSettableParameter` should be defined, it sounds like there is a need to  expand upon where it should be defined in the docs. For now, it is enough to say that `UserSettableParameter`s are utilized when defining the visualization server model parameters.

In essence, when defining the `ModulerServer` instance, you can use modifiable parameters like below (current example in Wolf Sheep example):
```
model_params = {"grass": UserSettableParameter('checkbox', 'Grass Enabled', True),
                "grass_regrowth_time": UserSettableParameter('slider', 'Grass Regrowth Time', 20, 1, 50),
                "initial_sheep": UserSettableParameter('slider', 'Initial Sheep Population', 100, 10, 300),
                "sheep_reproduce": UserSettableParameter('slider', 'Sheep Reproduction Rate', 0.04, 0.01, 1.0,
                                                         0.01),
                "initial_wolves": UserSettableParameter('slider', 'Initial Wolf Population', 50, 10, 300),
                "wolf_reproduce": UserSettableParameter('slider', 'Wolf Reproduction Rate', 0.05, 0.01, 1.0,
                                                        0.01,
                                                        description="The rate at which wolf agents reproduce."),
                "wolf_gain_from_food": UserSettableParameter('slider', 'Wolf Gain From Food Rate', 20, 1, 50),
                "sheep_gain_from_food": UserSettableParameter('slider', 'Sheep Gain From Food', 4, 1, 10)}

server = ModularServer(WolfSheepPredation, [canvas_element, chart_element], "Wolf Sheep Predation", model_params)
```
Now, if everything is happy with jQuery and the browser, then you should see the sidebar with the sliders. Otherwise, there may be issues...

**Comment by TaylorMutch** [comment]
@claywrc Please see #436 and see if that branch resolves any of the issues you are having.

**Comment by claywrc** [comment]
Will do.  I'm going to be working on this a lot this week, so I will give these a try.  Thanks!

**Comment by TaylorMutch** [comment]
@claywrc  Since I haven't heard any issues, I will close this issue. The bug fix branch, #436, has been merged into master.

**Comment by claywrc** [comment]
Sorry for the slow response.  Work on the updating the modular_template layout has slowed me down.  

I just updated to the latest mesa package and still no slider bars when using IE.  I've pretty much just defaulted to using Chrome.

Also - regarding the modular_template - nothing I changed in that file was showing up on the visualization, so I got to the point where I just deleted it (expecting it to cause an error), and it didn't appear to be a problem.  Is anything even calling that file?

**Comment by claywrc** [comment]
I should rephrase - I see where modular_template.html is being referenced, but since deleting it didn't make a difference, is that reference being overridden somewhere in the javascript?  Maybe in the bootstrap files?

**Comment by TaylorMutch** [comment]
@claywrc What version of IE are you using?

As far as the modular_template changes not being reflected in the browser, could you check if you have a local install of `mesa` included in your Python packages? I.e. Did you `pip install mesa`? If so, it's possible you might be calling that install's `modular_template.html` instead of the cloned repo's copy. If you're running a Python environment where this isn't the case, then I'd be *very* curious to see what the issue was.

You could be extra sure that you don't have a `pip install`ed version of mesa by uninstalling it and then seeing if the modified files are coming up or throwing errors (`pip uninstall mesa`).

**Comment by TaylorMutch** [comment]
@claywrc One issue you might be running into is that the current release of Mesa on PyPi does not include the fix for Edge. I just tested the bleeding edge repo and the fixes seems resolved in IE 11. You can try this by installing the master branch via `pip install git+https://github.com/projectmesa/mesa`.

**Comment by claywrc** [comment]
I did pip install mesa, but I went as far as deleting the local copy, and it didn't seem to matter, so that would suggest that it I am using the cloned-repo copy, correct?  This is where I'm pretty naive when it comes to developing from Git repositories, but I want to be able to edit my files locally and see those changes in my aplication (locally), so pip-installing and editing the local files should be the way to do that, right?  It sounds like maybe I'm doing something that is allowing the local changes to be overridden by remote sources?

Thanks for continuing to follow up - I appreciate the help, and I'm learning a lot, even if I still haven't figured things out yet.

**Comment by claywrc** [comment]
OK - I think I figured out what was going on, and I apologize for the confusion.  There were multiple installs of mesa in very different places on my machine (I'm still not sure how that happened).  The one that I had been trying to modify was not the one associated with my PATH variable, and so whatever I was doing there didn't matter.  Now that I know where the files are that ARE being called, I'm more optimistic about getting these things figured out.

**Comment by claywrc** [comment]
Given the above, I'm going to close this issue and I'll open a new, more specific one if I have additional problems with the slider bars or layout.

Thanks again.

**Comment by TaylorMutch** [comment]
@claywrc Thanks for updating! Glad you were able to figure it out.
