### ISSUE TITLE
Code is missing.

### ISSUE THREAD

**Issue by j-santoro** [projectmesa/mesa#939]
Hi. I have visited the mesa introduction page a few times to better understand how to use it and its properties, but it seems that some code for the sample model is missing now. Can you please check that to see that there aren't any errors in the introduction model, and the issue isn't on my end? Thanks!

**Comment by Sjnjerak** [comment]
I have the same issue, so whatever it is is not unique to j-santoro.
Thanks you to the developers, the package looks great, can't wait to try it!

**Comment by Sjnjerak** [comment]
@j-santoro meanwhile, the stable version of the documentation seems to have the code, you can access it here: https://mesa.readthedocs.io/en/stable/tutorials/intro_tutorial.html

**Comment by jackiekazil** [comment]
reviewing this conversation, it seems that it is resolved. I am going to close this ticket. If you have additional info that will help us fix this, please provide it.

**Comment by Corvince** [comment]
Unfortunately not yet resolved. The default view is now changed to stable so few people should run into this right now, but the code is still missing on the master docs branch.

There are two solutions: include ipython as a requirement for the readthedocs build or change the code lines from ipython3 to python. I tried the former but it is not yet working.

**Comment by jackiekazil** [comment]
ty for the catch.
